stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/data.csv
    - src/preprocess.py
    outs:
    - data/processed
  train:
    cmd: python src/train.py
    deps:
    - data/processed/train.csv
    - src/train.py
    params:
    - model_type
    outs:
    - models/model.joblib
  validate:
    cmd: python src/validate.py
    deps:
    - data/processed/test.csv
    - models/model.joblib
    - src/validate.py
    outs:
    - confusion_matrix.png
    - plots/confusion_matrix.csv
    metrics:
    - metrics.json
